title: Andrea Graglia
description: I am a self learned fullstack developer contractor, based in Quittengo, a beautiful and tiny village in the Italian Alps.
show_downloads: true
show_pdf_downloads: true
google_analytics:
theme: jekyll-theme-cayman
